### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Google\Cloud\Storage\StorageClient'

### ISSUE THREAD

**Issue by hardiklinksture** [auroraextensions/NickolasBurr_GoogleCloud#1]
Magento version 1.9.4.0
PHP version 7.2.13

Recently i install default magento and download plugin from 

> https://marketplace.magento.com/nickolasburr-nickolasburr-googlecloudstorage.html

 and 

> https://github.com/nickolasburr/googlecloudphpautoloader

After install successfully i go to Admin >> system >> configuration >> NICKOLAS BURR EXTENSIONS >> Google Cloud Storage

Then i got below error

`Fatal error: Uncaught Error: Class 'Google\Cloud\Storage\StorageClient' not found in /var/www/html/magento1940/app/code/community/NickolasBurr/GoogleCloudStorage/Helper/Storage.php:150 Stack trace: #0 /var/www/html/magento1940/app/Mage.php(550): NickolasBurr_GoogleCloudStorage_Helper_Storage->__construct() #1 /var/www/html/magento1940/app/code/community/NickolasBurr/GoogleCloudStorage/Model/Adminhtml/System/Config/Source/Bucket/Acl.php(27): Mage::helper('magegcs/storage') #2 /var/www/html/magento1940/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): NickolasBurr_GoogleCloudStorage_Model_Adminhtml_System_Config_Source_Bucket_Acl->toOptionArray(false) #3 /var/www/html/magento1940/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) #4 /var/www/html/magento1940/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage in /var/www/html/magento1940/app/code/community/NickolasBurr/GoogleCloudStorage/Helper/Storage.php on line 150`

Can you please help me how to resolve this error ?

Thanks.

**Comment by nickolasburr** [comment]
Hi @hardiklinksture, can you verify you've installed the Google Cloud PHP libraries via Composer? They should be installed to `lib/GoogleCloud`.

**Comment by nickolasburr** [comment]
Additionally, please make sure you've required `google/cloud-storage` in the `composer.json` file. I intentionally left the requirement out, as this module can be used for any of the Google Cloud PHP libraries. I will mention this information in the README.

The `composer.json` should have these updates:

```
  "require": {
    "php": ">=5.5",
    "mnsami/composer-custom-directory-installer": "1.1.*",
    "google/cloud-core": "~1.23",
    "google/cloud-storage": "~1.9"
  },
```

```
"extra": {
  "installer-paths": {
    "./google/cloud/core": ["google/cloud-core"],
    "./google/cloud/storage": ["google/cloud-storage"]
  }
}
```

**Comment by hardiklinksture** [comment]
i face new error 

```
a:5:{i:0;s:59:"Given keyfile at path /var/www/html/magento194/ was invalid";i:1;s:2477:"#0 /var/www/html/magento194/lib/GoogleCloud/google/cloud/core/src/ClientTrait.php(99): Google\Cloud\Storage\StorageClient->getKeyFile(Array)
#1 /var/www/html/magento194/google/cloud/storage/src/StorageClient.php(97): Google\Cloud\Storage\StorageClient->configureAuthentication(Array)
#2 /var/www/html/magento194/app/code/community/NickolasBurr/GoogleCloudStorage/Helper/Storage.php(150): Google\Cloud\Storage\StorageClient->__construct(Array)
#3 /var/www/html/magento194/app/Mage.php(550): NickolasBurr_GoogleCloudStorage_Helper_Storage->__construct()
#4 /var/www/html/magento194/app/code/community/NickolasBurr/GoogleCloudStorage/Model/Adminhtml/System/Config/Source/Bucket/Acl.php(27): Mage::helper('magegcs/storage')
#5 /var/www/html/magento194/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): NickolasBurr_GoogleCloudStorage_Model_Adminhtml_System_Config_Source_Bucket_Acl->toOptionArray(false)
#6 /var/www/html/magento194/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#7 /var/www/html/magento194/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#8 /var/www/html/magento194/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#9 /var/www/html/magento194/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#10 /var/www/html/magento194/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#11 /var/www/html/magento194/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#12 /var/www/html/magento194/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/html/magento194/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/html/magento194/app/Mage.php(686): Mage_Core_Model_App->run(Array)
#15 /var/www/html/magento194/index.php(83): Mage::run('', 'store')
#16 {main}";s:3:"url";s:100:"/magento194/index.php/admin/system_config/edit/section/magegcs/key/f37857abe92581c7ae1f6180352f4f3a/";s:11:"script_name";s:21:"/magento194/index.php";s:4:"skin";s:5:"admin";}
```

**Comment by nickolasburr** [comment]
You need to specify the path to the service account JSON key, which is used for authenticating with Google Cloud. You can find more information regarding setup in the [user manual](https://docs.nickolasburr.com/magento/extensions/1.x/magegcs/latest/manuals/UserManual.pdf).

**Comment by nickolasburr** [comment]
If you're still experiencing issues, please open a new issue.
